<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'About' => '',
  'Activate Your Account' => '',
  'Awaiting activation for {{email}}. {{resend}}' => '',
  'By:' => '',
  'By: {{author}}' => '',
  'Categories' => '',
  'Change Your Email Address' => '',
  'Change Your Information' => '',
  'Change Your Password' => '',
  'Create Your Account' => '',
  'Dashboard' => '',
  'Did you forget your password? Enter your email address below and we\'ll send you an email link that will allow you to reset your password.' => '',
  'Email Address' => '',
  'Enter Your Current Password' => '',
  'Enter the password to view this entry' => '',
  'Enter the password you registered with to activate your account.' => '',
  'Enter your current password to change your email address.' => '',
  'Enter your current password to make any changes to your account' => '',
  'Enter your new password twice to reset your password.' => '',
  'Error {{code}}' => '',
  'Facebook Settings' => '',
  'Facebook User ID' => '',
  'Forgot Your Password?' => '',
  'Google+ Settings' => '',
  'Heads Up!' => '',
  'Home' => '',
  'Login to Your Account' => '',
  'Manage Your Details' => '',
  'No Results Found' => '',
  'Number of Tweets to Fetch' => '',
  'Or register with one of these social networks' => '',
  'Or sign in with one of these social networks' => '',
  'Password' => '',
  'Read More' => '',
  'Recent Comments' => '',
  'Recent Facebook Stories' => '',
  'Recent Google+ Activities' => '',
  'Recent Posts' => '',
  'Recent Tweets' => '',
  'Register an Account' => '',
  'Registered' => '',
  'Related Posts' => '',
  'Reputation' => '',
  'Resend?' => '',
  'Reset Your Password' => '',
  'Sorry, we tried looking but we didn\'t find a match for the specified criteria. Try refining your search.' => '',
  'Submit' => '',
  'Tags' => '',
  'Thanks for Activating Your Account!' => '',
  'This Post is Password Protected' => '',
  'This user has not provided any information for themselves.' => '',
  'To accept your invitation, set your account details here.' => '',
  'Twitter Handle' => '',
  'Twitter Settings' => '',
  'Type to search, then press enter' => '',
  'Username' => '',
  'Woah!' => '',
  'You may now {{login}} and head to the {{dashboard}}' => '',
  'Your Google+ User ID' => '',
  'dashboard' => '',
  'edit' => '',
  'forgot' => '',
  'login' => '',
  'logout' => '',
  'register' => '',
  '{{headsup}} Looks like you\'re already logged in as {{email}}' => '',
  '{{headsup}} Looks like you\'re already logged in as {{email}}. You should {{logout}} before logging in to another account.' => '',
  '{{woah}} It looks like there aren\'t any posts in this category yet. Why don\'t you check out some of our other pages or check back later?' => '',
);
